import { Warband, ValidationResult, WarbandAbility } from '../models/types';
import { DataRepository } from './DataRepository';
import { CostEngine } from './CostEngine';
import { ValidationService } from './ValidationService';

/**
 * Warband Service
 * Orchestrates warband operations, coordinating between CostEngine, ValidationService, and DataRepository
 */
export class WarbandService {
  private repository: DataRepository;
  private costEngine: CostEngine;
  private validationService: ValidationService;

  constructor(repository: DataRepository) {
    this.repository = repository;
    this.costEngine = new CostEngine();
    this.validationService = new ValidationService();
  }

  /**
   * Creates a new warband with unique ID and initializes with zero cost
   * Requirements: 1.1, 1.2, 1.3, 1.4, 11.1, 11.2, 11.3
   */
  createWarband(data: {
    name: string;
    pointLimit: 75 | 125;
    ability: WarbandAbility;
  }): Warband {
    const warband: Warband = {
      id: '', // Will be generated by repository
      name: data.name,
      ability: data.ability,
      pointLimit: data.pointLimit,
      totalCost: 0, // Initialize with zero cost
      weirdos: [],
      createdAt: new Date(),
      updatedAt: new Date()
    };

    // Save to repository (generates ID and timestamps)
    return this.repository.saveWarband(warband);
  }

  /**
   * Retrieves a warband by ID from repository
   * Requirements: 12.1, 12.2
   */
  getWarband(id: string): Warband | null {
    return this.repository.loadWarband(id);
  }

  /**
   * Returns all warbands from repository
   * Requirements: 13.1
   */
  getAllWarbands(): Warband[] {
    return this.repository.loadAllWarbands();
  }

  /**
   * Updates a warband, recalculates costs, validates, and persists
   * Requirements: 11.4, 12.3, 12.4
   */
  updateWarband(id: string, data: Partial<Warband>): Warband {
    // Load existing warband
    const existingWarband = this.repository.loadWarband(id);
    if (!existingWarband) {
      throw new Error(`Warband not found: ${id}`);
    }

    // Merge updates
    const updatedWarband: Warband = {
      ...existingWarband,
      ...data,
      id: existingWarband.id, // Preserve ID
      createdAt: existingWarband.createdAt // Preserve creation date
    };

    // Recalculate costs for all weirdos
    for (const weirdo of updatedWarband.weirdos) {
      weirdo.totalCost = this.costEngine.calculateWeirdoCost(weirdo, updatedWarband.ability);
    }

    // Recalculate warband total cost
    updatedWarband.totalCost = this.costEngine.calculateWarbandCost(updatedWarband);

    // Save to repository
    return this.repository.saveWarband(updatedWarband);
  }

  /**
   * Deletes a warband from repository
   * Requirements: 14.2
   */
  deleteWarband(id: string): boolean {
    return this.repository.deleteWarband(id);
  }

  /**
   * Validates a warband against all game rules
   * Requirements: 12.4
   */
  validateWarband(warband: Warband): ValidationResult {
    return this.validationService.validateWarband(warband);
  }
}
